test.subjects<-read.table("../UCI HAR Dataset/test/subject_test.txt", col.names=c("subject"))
test.activity<-read.table("../UCI HAR Dataset/test/y_test.txt", col.names=c("activity"))
test.features<-read.table("../UCI HAR Dataset/test/X_test.txt")
test.body_acc_x<-read.table("../UCI HAR Dataset/test/Inertial Signals/body_acc_x_test.txt")
test.body_acc_y<-read.table("../UCI HAR Dataset/test/Inertial Signals/body_acc_y_test.txt")
test.body_acc_z<-read.table("../UCI HAR Dataset/test/Inertial Signals/body_acc_z_test.txt")
test.body_gyro_x<-read.table("../UCI HAR Dataset/test/Inertial Signals/body_gyro_x_test.txt")
test.body_gyro_y<-read.table("../UCI HAR Dataset/test/Inertial Signals/body_gyro_y_test.txt")
test.body_gyro_z<-read.table("../UCI HAR Dataset/test/Inertial Signals/body_gyro_z_test.txt")
test.total_acc_x<-read.table("../UCI HAR Dataset/test/Inertial Signals/total_acc_x_test.txt")
test.total_acc_y<-read.table("../UCI HAR Dataset/test/Inertial Signals/total_acc_y_test.txt")
test.total_acc_z<-read.table("../UCI HAR Dataset/test/Inertial Signals/total_acc_z_test.txt")
alltest<-cbind(test.subjects, test.activity, test.features, test.body_acc_x, test.body_acc_y, test.body_acc_z,test.body_gyro_x, test.body_gyro_y, test.body_gyro_z,test.total_acc_x, test.total_acc_y, test.total_acc_z)


train.subjects<-read.table("../UCI HAR Dataset/train/subject_train.txt", col.names=c("subject"))
train.activity<-read.table("../UCI HAR Dataset/train/y_train.txt", col.names=c("activity"))
train.features<-read.table("../UCI HAR Dataset/train/X_train.txt")
train.body_acc_x<-read.table("../UCI HAR Dataset/train/Inertial Signals/body_acc_x_train.txt")
train.body_acc_y<-read.table("../UCI HAR Dataset/train/Inertial Signals/body_acc_y_train.txt")
train.body_acc_z<-read.table("../UCI HAR Dataset/train/Inertial Signals/body_acc_z_train.txt")
train.body_gyro_x<-read.table("../UCI HAR Dataset/train/Inertial Signals/body_gyro_x_train.txt")
train.body_gyro_y<-read.table("../UCI HAR Dataset/train/Inertial Signals/body_gyro_y_train.txt")
train.body_gyro_z<-read.table("../UCI HAR Dataset/train/Inertial Signals/body_gyro_z_train.txt")
train.total_acc_x<-read.table("../UCI HAR Dataset/train/Inertial Signals/total_acc_x_train.txt")
train.total_acc_y<-read.table("../UCI HAR Dataset/train/Inertial Signals/total_acc_y_train.txt")
train.total_acc_z<-read.table("../UCI HAR Dataset/train/Inertial Signals/total_acc_z_train.txt")
alltrain<-cbind(train.subjects, train.activity, train.features, train.body_acc_x, train.body_acc_y, train.body_acc_z,train.body_gyro_x, train.body_gyro_y, train.body_gyro_z,train.total_acc_x, train.total_acc_y, train.total_acc_z)

tidydata<-rbind(alltest, alltrain)
